### ISSUE TITLE
Page URL

### ISSUE THREAD

**Issue by zhuoyanlee** [AusDVA/myservice-prototype#1001]
The link on the sitemap should point to the actual URL on heroku rather than the file path itself

https://github.com/AusDVA/myservice-prototype/blob/c191f8e81483bf32e9f0cb0c0d10ba422453e6dc/index.js#L130

**Comment by sitrobotsit** [comment]
http://myservice-disco.herokuapp.com/sitemap builds the links based on root relative, which makes it domain agnostic. I also think it's cleaner and focuses attention on the most valuable part of the url.

**Comment by AllySummers** [comment]
hey @zhuoyanlee - been a while since you replied. could you provide clarification?

**Comment by zhuoyanlee** [comment]
ok. Actually clicking on the EJS link works anyway
