### ISSUE TITLE
5 pages for auth/healthcard need to be refined into one page with states

### ISSUE THREAD

**Issue by mattmcinerney** [AusDVA/myservice-prototype#1009]
The following 5 pages should be refactored into states on the healthcard index page:

/auth/healthcard/healthcard-gold.ejs
/auth/healthcard/healthcard-has-card.ejs
/auth/healthcard/healthcard-nlhc.ejs
/auth/healthcard/healthcard-no-card.ejs
/auth/healthcard/healthcard-none.ejs
/auth/healthcard/index.ejs

This was discussed during a code-pruning session, the benefit provided by this refactor will be to reduce clutter within the code base.

**Comment by AllySummers** [comment]
@mattmcinerney is this needed since the introduction of multiple cards?

**Comment by AllySummers** [comment]
@treborsantiago do these old pages need to exist since the introduction of the new multiple cards page?
