### ISSUE TITLE
font awesome icons in the mobile menu are the incorrect width

### ISSUE THREAD

**Issue by mattmcinerney** [AusDVA/myservice-prototype#1043]
The font awesome icons in the angular app are not aligned or spaced equally.

This bug is due to a difference in the way font awesome is rendered in the prototype compared to in angular.

The fix should be to add the 'fa-fw' class. If this fix doesn't work the basic premise is that the icons need to all be the same width.

**Comment by treborsantiago** [comment]
Fix resolved mobile but adversely effected desktop view. Icons are now aligning to left of label.

**Comment by AllySummers** [comment]
@mattmcinerney @treborsantiago can this be marked as resolved?
