### ISSUE TITLE
Missing chevron on payments widget

### ISSUE THREAD

**Issue by SamMonaghan** [AusDVA/myservice-prototype#1051]
![image](https://user-images.githubusercontent.com/21096715/59507179-9e8dd780-8eed-11e9-9250-ac375f44b9f3.png)

Looks like possibly a missing colour definition?

This is the applied class in the disco prototype
.widget-tile--blue-mid .payment-amount, .widget-tile--blue-mid .widget-tile__title-icon {
    color: #fff;
}

**Comment by mattmcinerney** [comment]
Resolved in the latest merge
