### ISSUE TITLE
Password 'show' button not aligned within input field

### ISSUE THREAD

**Issue by SamMonaghan** [AusDVA/myservice-prototype#1060]
See the image below - the original 'show' button was placed inside the input element on the far right.

See https://myservice-disco.herokuapp.com/auth/mygov/mygov-login for the page in question.

![image](https://user-images.githubusercontent.com/21096715/59902406-764c2e80-9441-11e9-952e-d08c432417cf.png)

**Comment by mattmcinerney** [comment]
This has been fixed and merged into the angular app by Abhi -> work completed in this branch: https://github.com/AusDVA/myservice-prototype/tree/bug/0000/show-button-mygov-login
